#!/usr/bin/env python
import pygtk
pygtk.require('2.0')

import gtk
import gnome
import gnome.ui
import gconf
import gettext
_ = gettext.gettext

from gnomeblog import blog_poster
from gnomeblog import blogger_prefs
from gnomeblog import gnome_blog_globals

#FIXME: need to get this path from auto*
gettext.bindtextdomain('gnome-blog', gnome_blog_globals.localedir)
gettext.textdomain('gnome-blog')
    
gtk.window_set_default_icon_name('gnome-blog')
        
class BloggerApp:
    def __init__(self):
        self.prefs_key = "/apps/gnome-blog"

        client = gconf.client_get_default()
        value = client.get_bool(self.prefs_key + "/initialized")

        accel_group = gtk.AccelGroup()

        poster = blog_poster.BlogPoster(prefs_key=self.prefs_key,
                                        accel_group=accel_group,
                                        on_entry_posted=self._onEntryPosted)

        if (value == None or value == False):
            poster._showPrefDialog()
            client.set_bool(self.prefs_key + "/initialized", True)
        
        poster_window = gtk.Window(gtk.WINDOW_TOPLEVEL)
        poster_window.set_title(_("Post Blog Entry"))
        poster_window.connect('destroy', lambda w: gtk.main_quit())
        poster_window.add_accel_group(accel_group)

        poster_window.add(poster)
        poster_window.show_all()

    def _onEntryPosted(self):
        gtk.main_quit()
        
app = BloggerApp()
gtk.main()
